# Laboratorio 4-03: Algoritmo QR

Samantha Sánchez Tinoco

In [1]:
import numpy as np

In [5]:
def gram_schmidt(A):
    
    n = A.shape[0]
    Q = np.zeros_like(A, dtype=float)
    R = np.zeros((n, n), dtype=float)
    
    for j in range(n):
        v = A[:, j].astype(float)  # Asegurar tipo float
        for i in range(j):
            R[i, j] = np.dot(Q[:, i], A[:, j])
            v -= R[i, j] * Q[:, i]
        R[j, j] = np.linalg.norm(v)
        Q[:, j] = v / R[j, j]
    
    return Q, R

In [ ]:
def algoritmo_qr_simple(matriz, tolerancia=1e-6):

    n = matriz.shape[0]
    acumulador_vectores = np.eye(n, dtype=float)

    while True:
        # Hacer QR usando Gram-Schmidt
        Q, R = gram_schmidt(matriz)
        matriz_siguiente = R @ Q
        
        # Vctores propios
        acumulador_vectores = acumulador_vectores @ Q
        
        # Convergencia
        if np.allclose(matriz, matriz_siguiente, atol=tolerancia):
            break
        matriz = matriz_siguiente

    # Valores propios en la diagonal de la matriz 
    valores_propios = np.diag(matriz)
    vectores_propios = acumulador_vectores
    return valores_propios, vectores_propios


In [ ]:
A = np.array([
    [8, 3, 1, 7],
    [3, 3, 5, 4],
    [1, 5, 4, -2],
    [7, 4, -2, 2]
], dtype=float) 

valores_propios, vectores_propios = algoritmo_qr_simple(A)

print("Valores propios:")
print(valores_propios)
print("\nVectores propios:")
print(vectores_propios)

Valores propios:
[14.83555948  7.34315248 -5.19461582  0.01590386]

Vectores propios:
[[ 0.72978427 -0.26092224  0.27964626 -0.56668551]
 [ 0.42808536  0.46723501  0.50547483  0.58560189]
 [ 0.17174283  0.79372769 -0.45299251 -0.36782949]
 [ 0.5046407  -0.28914942 -0.67903679  0.44792792]]
