# Laboratorio 4

Samantha Sánchez Tinoco

In [1]:
import numpy as np

1. Factorización LDL<sup>t</sup>

In [3]:
def factorizacion_LDL(A):
    # Convertir A a un arreglo de punto flotante
    A = np.array(A, dtype=float)
    
    # Inicializar L y D
    n = len(A)
    L = np.eye(n)  # L comienza como una matriz identidad
    D = np.zeros(n) # D comienza con solamente ceros

    # Algoritmo de factorización LDL^T
    for i in range(n):
        # Calcular el valor de los valores que van en D
        D[i] = A[i, i] - sum(L[i, k]**2 * D[k] for k in range(i))
        
        if D[i] <= 0:
            # Comprobar si la matriz es definida positiva de manera indirecta
            # Todos los elementos de D deben de ser positivos
            print("La factorización no es posible.")
            return None, None
        
        for j in range(i+1, n):
            # Calcular los elementos de L
            L[j, i] = (A[j, i] - sum(L[j, k] * L[i, k] * D[k] for k in range(i))) / D[i]

    # Construir la matriz D diagonal
    matriz_D = np.diag(D)
    
    return L,matriz_D

In [4]:
# Comprobar con una matriz definida positiva

A = [[4, 12, -16],
     [12, 37, -43],
     [-16, -43, 98]]

L, D = factorizacion_LDL(A)

print("Matriz L:")
print(L)
print("\nMatriz D:")
print(D)

Matriz L:
[[ 1.  0.  0.]
 [ 3.  1.  0.]
 [-4.  5.  1.]]

Matriz D:
[[4. 0. 0.]
 [0. 1. 0.]
 [0. 0. 9.]]


2. Factorización LL<sup>t</sup> (Factorización de Cholesky)

In [6]:
def factorizacion_cholesky(A):
    # Convertir A a un arreglo de punto flotante
    A = np.array(A, dtype=float)
    n = len(A)
    
    # Inicializar L con ceros y de tamaño n x n
    L = np.zeros((n, n))

    # Algoritmo de factorización de Cholesky
    for i in range(n):
        for j in range(i+1): 
            if i == j:
                # Calcular los elementos de la diagonal
                sum_diagonal = sum(L[i, k]**2 for k in range(i))  # Suma de cuadrados de elementos antes de la fila i
                L[i, j] = np.sqrt(A[i, i] - sum_diagonal) 
                
                # Verificar si el valor en la diagonal es positivo
                if L[i, j] <= 0:
                    print("La factorización no posible.")
                    return None
            else:
                # Calcular los elementos que no están en la diagonal
                sum_no_diagonal = sum(L[i, k] * L[j, k] for k in range(j))  # Suma de productos previos de las filas i y j
                L[i, j] = (A[i, j] - sum_no_diagonal) / L[j, j]

    return L

In [7]:
# Comprobar el funcionamiento del código

A = [[4, 12, -16], 
     [12, 37, -43],
     [-16, -43, 98]]

L = factorizacion_cholesky(A)

print("Matriz L:")
print(L)

Matriz L:
[[ 2.  0.  0.]
 [ 6.  1.  0.]
 [-8.  5.  3.]]
