# Laboratorio 1-02

Samantha Sánchez Tinoco

1. Calcule la inversa de la matriz A empleando la función inv de la biblioteca linalg y guarde el resultado en la variable B.

![Matriz A](Labo1-02.png)

In [4]:
import numpy as np
import numpy.linalg as la

#Declarar la matriz A
A=np.array([[1.32,3.25,2.77],[-3.57,2.12,3.26],[-9.87,3.33,2.15]])
A

array([[ 1.32,  3.25,  2.77],
       [-3.57,  2.12,  3.26],
       [-9.87,  3.33,  2.15]])

In [5]:
#Calcular la inversa de A
B = la.inv(A)
B

array([[ 0.10010838, -0.03555248, -0.07506936],
       [ 0.38945748, -0.47970094,  0.22559435],
       [-0.14363894,  0.57976799, -0.22891339]])

2. Multiplique la matriz por su inversa con la instrucción A@B. El símbolo @ indica la multiplicación matricial.

In [6]:
#Multiplicar A por B
A@B

array([[ 1.00000000e+00, -4.29919568e-17,  5.67183920e-17],
       [ 3.89451548e-17,  1.00000000e+00,  8.26576256e-17],
       [-1.05203495e-16, -7.08482088e-18,  1.00000000e+00]])

3. Verifique el resultado de multiplicar AA<sup>-1</sup> empleando cinco matrices distintas. Utilice números no enteros para las componentes de la matriz

In [11]:
# Definir cinco matrices distintas con componentes no enteras
matrices = [
    np.array([[2.5, 2.4], [4.1, 4.8]]),
    np.array([[1.2, 1.9, 4.6], [3.5, 4.1, 5.8], [5.8, 6.1, 8.4]]),
    np.array([[3.4, 1.3], [4.3, 2.9]]),
    np.array([[2.6, 3.2, 3.6], [5.3, 5.2, 6.9], [8.7, 8.5, 9.7]]),
    np.array([[1.9, 1.4], [3.6, 3.9]])
]

# Calcular la inversa de cada matriz y hacer la multiplicación
for i, A in enumerate(matrices):
    A_inv = np.linalg.inv(A)
    I = np.dot(A, A_inv)
    
    # Imprimir los resultados
    print(f"Matriz A{i+1}:")
    print(A)
    print()
    print(f"A{i+1}A{i+1}^-1:")
    print(I)
    print()

Matriz A1:
[[2.5 2.4]
 [4.1 4.8]]

A1A1^-1:
[[ 1.00000000e+00  6.07744308e-16]
 [-3.73363891e-16  1.00000000e+00]]

Matriz A2:
[[1.2 1.9 4.6]
 [3.5 4.1 5.8]
 [5.8 6.1 8.4]]

A2A2^-1:
[[ 1.00000000e+00 -2.45816439e-16  3.43881786e-16]
 [ 7.60698694e-17  1.00000000e+00  1.17114162e-15]
 [-1.52139739e-16  8.00927951e-16  1.00000000e+00]]

Matriz A3:
[[3.4 1.3]
 [4.3 2.9]]

A3A3^-1:
[[ 1.00000000e+00 -1.64479411e-16]
 [-2.21420592e-16  1.00000000e+00]]

Matriz A4:
[[2.6 3.2 3.6]
 [5.3 5.2 6.9]
 [8.7 8.5 9.7]]

A4A4^-1:
[[ 1.00000000e+00  3.58245822e-16 -2.77056016e-16]
 [ 4.50670540e-16  1.00000000e+00 -5.35121901e-17]
 [ 5.45418300e-16  5.75724800e-16  1.00000000e+00]]

Matriz A5:
[[1.9 1.4]
 [3.6 3.9]]

A5A5^-1:
[[1.00000000e+00 1.28635967e-16]
 [1.79322099e-16 1.00000000e+00]]

