# Laboratorio 4-02: Método de la potencia inversa

Samantha Sánchez Tinoco

In [1]:
import numpy as np

In [2]:
def metodo_potencia_inversa(A):
    def multiplicar_matriz_vector(M, v):
        # Multiplicar matriz por vecor
        return [sum(M[i][j] * v[j] for j in range(len(v))) for i in range(len(M))]

    def normalizar(v):
        # Normalizar el vector
        norma = sum(x**2 for x in v) ** 0.5
        return [x / norma for x in v]

    def sustitucion_hacia_atras(U, b):
        # Resolver tringular superior
        n = len(U)
        x = [0] * n
        for i in range(n - 1, -1, -1):
            x[i] = (b[i] - sum(U[i][j] * x[j] for j in range(i + 1, n))) / U[i][i]
        return x

    def descomposicion_LU(M):
        # Descomponer la matriz
        n = len(M)
        L = [[0 if i != j else 1 for j in range(n)] for i in range(n)]
        U = [[0] * n for _ in range(n)]
        
        for i in range(n):
            for j in range(i, n):
                U[i][j] = M[i][j] - sum(L[i][k] * U[k][j] for k in range(i))
            for j in range(i + 1, n):
                L[j][i] = (M[j][i] - sum(L[j][k] * U[k][i] for k in range(i))) / U[i][i]
        return L, U

    def resolver_LU(L, U, b):
        # Resolver por sustitució
        n = len(L)
        y = [0] * n
        for i in range(n):
            y[i] = (b[i] - sum(L[i][j] * y[j] for j in range(i)))
        return sustitucion_hacia_atras(U, y)

    n = len(A)
    valores_propios = []
    vectores_propios = []
    L, U = descomposicion_LU(A) 

    for _ in range(n):  # Calcular cada vector y valor propio
        x = [1] * n  # Vector inicial
        lambda_anterior = 0
        while True: 
            b = resolver_LU(L, U, x)
            x = normalizar(b)
            lambda_actual = sum(x[i] * sum(A[i][j] * x[j] for j in range(n)) for i in range(n))

            if abs(lambda_actual - lambda_anterior) < 10e-7:
                break
            lambda_anterior = lambda_actual

        valores_propios.append(lambda_actual)
        vectores_propios.append(x)

        A = [[A[i][j] - lambda_actual * x[i] * x[j] for j in range(n)] for i in range(n)]
        L, U = descomposicion_LU(A) 

    return valores_propios, vectores_propios


In [3]:
# Matriz ejemplo
A = [[17, 1, 2],
    [1, 14, -2],
    [2, -2, 20]]

valores_propios, vectores_propios = metodo_potencia_inversa(A)

print("Valores propios (potencia inversa):")
print(valores_propios)
print("\nVectores propios (potencia inversa):")
for vec in vectores_propios:
    print(vec)


Valores propios (potencia inversa):
[12.785415694942772, -2.2898395557210427e-07, -9.445097303101466e-15]

Vectores propios (potencia inversa):
[-0.3669751869500998, 0.8652671019347979, 0.34152899506820117]
[0.36707415609359645, -0.8652135661158056, -0.34155826580152404]
[0.367074136380972, -0.865213571216847, -0.34155827406513445]


In [ ]:
# Comparar los resultados con las funciones de numpy

A = np.array([
    [17, 1, 2],
    [1, 14, -2],
    [2, -2, 20]])

valores_propios, vectores_propios = np.linalg.eig(A)

print("Valores propios (NumPy):")
print(valores_propios)
print("\nVectores propios (NumPy):")
for vec in vectores_propios.T:
    print(vec)

Valores propios (NumPy):
[21.27015032 16.94443491 12.78541476]

Vectores propios (NumPy):
[-0.37763858  0.1969546  -0.90476405]
[-0.84995438 -0.46141023  0.25431901]
[ 0.36737809 -0.86504883 -0.34164873]
